import { normalizeLabel } from './text';

// Synonymes d'aliments : alias (formulation libre) → slug catalogue canonique.
// Couvre les formulations courantes des recettes IA que le match exact ne capte
// pas : coupes (« filet de poulet » → poulet), qualificatifs (« persil frais »,
// « poivre moulu »), variantes (« moutarde de Dijon » → moutarde). Conservateur :
// chaque alias pointe vers un aliment réellement présent au catalogue (0009/0012),
// donc pas de faux rayon. À enrichir au fil de l'usage.
const SYNONYM_PAIRS: ReadonlyArray<readonly [string, string]> = [
  // Volaille & viandes — coupes
  ['filet de poulet', 'blanc-poulet'],
  ['escalope de poulet', 'blanc-poulet'],
  ['poitrine de poulet', 'blanc-poulet'],
  ['aiguillettes de poulet', 'blanc-poulet'],
  ['suprême de poulet', 'blanc-poulet'],
  ['pilon de poulet', 'cuisse-poulet'],
  ['haut de cuisse de poulet', 'cuisse-poulet'],
  ['blanc de dinde', 'escalope-dinde'],
  ['filet de dinde', 'escalope-dinde'],
  ['steak haché', 'boeuf-hache'],
  ['viande hachée', 'boeuf-hache'],
  ['hachis de boeuf', 'boeuf-hache'],
  ['filet de boeuf', 'boeuf'],
  ['pavé de boeuf', 'boeuf'],
  ['viande de boeuf', 'boeuf'],
  ['sauté de boeuf', 'boeuf'],
  ['sauté de porc', 'porc'],
  ['filet de porc', 'porc'],
  ['échine de porc', 'porc'],
  ['lardons fumés', 'lardons'],
  ['jambon blanc', 'jambon'],
  ['jambon cuit', 'jambon'],
  ['souris d agneau', 'gigot'],
  // Poissons & fruits de mer
  ['filet de saumon', 'saumon'],
  ['pavé de saumon', 'saumon'],
  ['darne de saumon', 'saumon'],
  ['filet de cabillaud', 'cabillaud'],
  ['dos de cabillaud', 'cabillaud'],
  ['pavé de cabillaud', 'cabillaud'],
  ['filet de colin', 'colin'],
  ['filet de poisson blanc', 'filet-poisson'],
  ['thon en boîte', 'thon-boite'],
  ['thon en conserve', 'thon-boite'],
  ['thon au naturel', 'thon-boite'],
  ['crevettes roses', 'crevette'],
  ['crevettes décortiquées', 'crevette'],
  ['gambas crues', 'gambas'],
  // Crémerie & œufs
  ['jaune d oeuf', 'oeufs'],
  ['blanc d oeuf', 'oeufs'],
  ['jaunes d oeufs', 'oeufs'],
  ['blancs d oeufs', 'oeufs'],
  ['yaourt', 'yaourt-nature'],
  ['beurre doux', 'beurre'],
  ['beurre demi-sel', 'beurre'],
  ['beurre mou', 'beurre'],
  ['beurre fondu', 'beurre'],
  ['crème entière', 'creme-fraiche'],
  ['crème épaisse', 'creme-fraiche'],
  ['crème fraîche épaisse', 'creme-fraiche'],
  ['crème fleurette', 'creme-liquide'],
  ['crème fraîche liquide', 'creme-liquide'],
  ['emmental râpé', 'fromage-rape'],
  ['gruyère râpé', 'fromage-rape'],
  ['parmesan râpé', 'parmesan'],
  ['boule de mozzarella', 'mozzarella'],
  ['mozzarella di bufala', 'mozzarella'],
  // Légumes, fruits & aromates
  ['gousse d ail', 'ail'],
  ['gousses d ail', 'ail'],
  ['ail haché', 'ail'],
  ['ail émincé', 'ail'],
  ['oignon jaune', 'oignon'],
  ['oignon blanc', 'oignon'],
  ['oignon nouveau', 'oignon'],
  ['oignon vert', 'oignon'],
  ['cébette', 'oignon'],
  ['patate', 'pomme-de-terre'],
  ['patates', 'pomme-de-terre'],
  ['champignon de paris', 'champignon'],
  ['champignons de paris', 'champignon'],
  ['persil frais', 'persil'],
  ['persil plat', 'persil'],
  ['persil frisé', 'persil'],
  ['basilic frais', 'basilic'],
  ['coriandre fraîche', 'coriandre'],
  ['menthe fraîche', 'menthe'],
  ['gingembre frais', 'gingembre'],
  ['thym frais', 'thym'],
  ['branche de thym', 'thym'],
  ['brins de thym', 'thym'],
  ['romarin frais', 'romarin'],
  ['feuille de laurier', 'laurier'],
  ['feuilles de laurier', 'laurier'],
  ['jus de citron', 'citron'],
  ['zeste de citron', 'citron'],
  ['jus de citron vert', 'citron-vert'],
  ['zeste de citron vert', 'citron-vert'],
  // Épicerie & condiments
  ['moutarde de dijon', 'moutarde'],
  ['moutarde à l ancienne', 'moutarde'],
  ['moutarde forte', 'moutarde'],
  ['tomate concassée', 'tomates-concassees'],
  ['pulpe de tomate', 'tomates-concassees'],
  ['tomates en dés', 'tomates-concassees'],
  ['dés de tomates', 'tomates-concassees'],
  ['double concentré de tomate', 'concentre-tomate'],
  ['cube de bouillon de boeuf', 'bouillon-boeuf'],
  ['bouillon de poule', 'bouillon-volaille'],
  ['cube de bouillon', 'bouillon-cube'],
  ['gingembre en poudre', 'gingembre-moulu'],
  ['noix de muscade', 'muscade'],
  ['huile d olive vierge', 'huile-olive'],
  ['huile d olive extra vierge', 'huile-olive'],
  ['huile végétale', 'huile-tournesol'],
  ['huile neutre', 'huile-tournesol'],
  ['vinaigre de vin', 'vinaigre'],
  ['vinaigre blanc', 'vinaigre'],
  ['sauce de soja', 'sauce-soja'],
  ['sel fin', 'sel'],
  ['gros sel', 'sel'],
  ['sel de mer', 'sel'],
  ['fleur de sel', 'sel'],
  ['poivre noir', 'poivre'],
  ['poivre moulu', 'poivre'],
  ['poivre du moulin', 'poivre'],
  ['sucre en poudre', 'sucre'],
  ['sucre blanc', 'sucre'],
  ['sucre semoule', 'sucre'],
  ['levure chimique', 'levure'],
  ['levure de boulanger', 'levure'],
  ['levure boulangère', 'levure'],
  ['farine de blé', 'farine'],
  ['avoine', 'flocons-avoine'],
  ['nutella', 'pate-a-tartiner'],
  // Pluriels en -x (normalizeLabel ne retire que le -s) & graphies courantes
  ['poireaux', 'poireau'],
  ['choux', 'chou'],
  ['choux de bruxelles', 'chou-bruxelles'],
  ['choux-fleurs', 'chou-fleur'],
  ['laurel', 'laurier'],
];

/** Map normalisée (normalizeLabel(alias) → slug). Construite une fois au chargement. */
export const SYNONYM_TO_SLUG: ReadonlyMap<string, string> = (() => {
  const m = new Map<string, string>();
  for (const [alias, slug] of SYNONYM_PAIRS) m.set(normalizeLabel(alias), slug);
  return m;
})();
