-- =============================================================================
-- Mealing — Chantier D (suite) : élargissement du catalogue d'aliments FR
-- =============================================================================
-- Étend le catalogue de base (0009) pour réduire les articles non classés
-- (« Autres ») dans la liste de courses, en couvrant les staples FR courants
-- des recettes et ajouts. Identité stable : source 'manual', external_id
-- 'cat:<slug>'. `category` = CLÉ stable (cf. 0011 / product-assets), pas un
-- libellé. Idempotent (ON CONFLICT DO UPDATE). Précision approximative assumée
-- (principe n°2) : unités par défaut « au mieux ».
-- =============================================================================

insert into public.food (name, source, external_id, default_unit, category) values
  -- Fruits & légumes — fruits
  ('Poire',                 'manual', 'cat:poire',             'pièce', 'legumes'),
  ('Raisin',                'manual', 'cat:raisin',            'g',     'legumes'),
  ('Pêche',                 'manual', 'cat:peche',             'pièce', 'legumes'),
  ('Abricot',               'manual', 'cat:abricot',           'pièce', 'legumes'),
  ('Nectarine',             'manual', 'cat:nectarine',         'pièce', 'legumes'),
  ('Prune',                 'manual', 'cat:prune',             'pièce', 'legumes'),
  ('Cerise',                'manual', 'cat:cerise',            'g',     'legumes'),
  ('Kiwi',                  'manual', 'cat:kiwi',              'pièce', 'legumes'),
  ('Ananas',                'manual', 'cat:ananas',            'pièce', 'legumes'),
  ('Mangue',                'manual', 'cat:mangue',            'pièce', 'legumes'),
  ('Melon',                 'manual', 'cat:melon',             'pièce', 'legumes'),
  ('Pastèque',              'manual', 'cat:pasteque',          'pièce', 'legumes'),
  ('Framboise',             'manual', 'cat:framboise',         'g',     'legumes'),
  ('Myrtille',              'manual', 'cat:myrtille',          'g',     'legumes'),
  ('Clémentine',            'manual', 'cat:clementine',        'pièce', 'legumes'),
  ('Mandarine',             'manual', 'cat:mandarine',         'pièce', 'legumes'),
  ('Pamplemousse',          'manual', 'cat:pamplemousse',      'pièce', 'legumes'),
  ('Citron vert',           'manual', 'cat:citron-vert',       'pièce', 'legumes'),
  ('Grenade',               'manual', 'cat:grenade',           'pièce', 'legumes'),
  ('Figue',                 'manual', 'cat:figue',             'pièce', 'legumes'),
  ('Rhubarbe',              'manual', 'cat:rhubarbe',          'g',     'legumes'),
  -- Fruits & légumes — légumes
  ('Tomate cerise',         'manual', 'cat:tomate-cerise',     'g',     'legumes'),
  ('Patate douce',          'manual', 'cat:patate-douce',      'g',     'legumes'),
  ('Oignon rouge',          'manual', 'cat:oignon-rouge',      'pièce', 'legumes'),
  ('Poireau',               'manual', 'cat:poireau',           'pièce', 'legumes'),
  ('Aubergine',             'manual', 'cat:aubergine',         'pièce', 'legumes'),
  ('Chou',                  'manual', 'cat:chou',              'pièce', 'legumes'),
  ('Chou-fleur',            'manual', 'cat:chou-fleur',        'pièce', 'legumes'),
  ('Chou rouge',            'manual', 'cat:chou-rouge',        'pièce', 'legumes'),
  ('Chou de Bruxelles',     'manual', 'cat:chou-bruxelles',    'g',     'legumes'),
  ('Maïs',                  'manual', 'cat:mais',              'g',     'legumes'),
  ('Petits pois',           'manual', 'cat:petits-pois',       'g',     'legumes'),
  ('Betterave',             'manual', 'cat:betterave',         'pièce', 'legumes'),
  ('Navet',                 'manual', 'cat:navet',             'pièce', 'legumes'),
  ('Radis',                 'manual', 'cat:radis',             'botte', 'legumes'),
  ('Fenouil',               'manual', 'cat:fenouil',           'pièce', 'legumes'),
  ('Céleri',                'manual', 'cat:celeri',            'pièce', 'legumes'),
  ('Céleri-rave',           'manual', 'cat:celeri-rave',       'pièce', 'legumes'),
  ('Asperge',               'manual', 'cat:asperge',           'botte', 'legumes'),
  ('Artichaut',             'manual', 'cat:artichaut',         'pièce', 'legumes'),
  ('Courge',                'manual', 'cat:courge',            'g',     'legumes'),
  ('Potiron',               'manual', 'cat:potiron',           'g',     'legumes'),
  ('Butternut',             'manual', 'cat:butternut',         'pièce', 'legumes'),
  ('Panais',                'manual', 'cat:panais',            'pièce', 'legumes'),
  ('Endive',                'manual', 'cat:endive',            'pièce', 'legumes'),
  ('Mâche',                 'manual', 'cat:mache',             'g',     'legumes'),
  ('Roquette',              'manual', 'cat:roquette',          'g',     'legumes'),
  ('Blette',                'manual', 'cat:blette',            'botte', 'legumes'),
  ('Fève',                  'manual', 'cat:feve',              'g',     'legumes'),
  ('Gingembre',             'manual', 'cat:gingembre',         'g',     'legumes'),
  ('Piment',                'manual', 'cat:piment',            'pièce', 'legumes'),
  -- Fruits & légumes — herbes fraîches
  ('Coriandre',             'manual', 'cat:coriandre',         'botte', 'legumes'),
  ('Ciboulette',            'manual', 'cat:ciboulette',        'botte', 'legumes'),
  ('Menthe',                'manual', 'cat:menthe',            'botte', 'legumes'),
  ('Thym',                  'manual', 'cat:thym',              'botte', 'legumes'),
  ('Romarin',               'manual', 'cat:romarin',           'botte', 'legumes'),
  ('Laurier',               'manual', 'cat:laurier',           'botte', 'legumes'),
  ('Origan',                'manual', 'cat:origan',            'botte', 'legumes'),
  ('Aneth',                 'manual', 'cat:aneth',             'botte', 'legumes'),
  ('Estragon',              'manual', 'cat:estragon',          'botte', 'legumes'),
  ('Sauge',                 'manual', 'cat:sauge',             'botte', 'legumes'),
  -- Viandes & poissons — viandes
  ('Blanc de poulet',       'manual', 'cat:blanc-poulet',      'g',     'proteines'),
  ('Cuisse de poulet',      'manual', 'cat:cuisse-poulet',     'pièce', 'proteines'),
  ('Dinde',                 'manual', 'cat:dinde',             'g',     'proteines'),
  ('Escalope de dinde',     'manual', 'cat:escalope-dinde',    'pièce', 'proteines'),
  ('Bœuf',                  'manual', 'cat:boeuf',             'g',     'proteines'),
  ('Rôti de bœuf',          'manual', 'cat:roti-boeuf',        'g',     'proteines'),
  ('Entrecôte',             'manual', 'cat:entrecote',         'pièce', 'proteines'),
  ('Bavette',               'manual', 'cat:bavette',           'pièce', 'proteines'),
  ('Porc',                  'manual', 'cat:porc',              'g',     'proteines'),
  ('Côte de porc',          'manual', 'cat:cote-porc',         'pièce', 'proteines'),
  ('Filet mignon',          'manual', 'cat:filet-mignon',      'g',     'proteines'),
  ('Rôti de porc',          'manual', 'cat:roti-porc',         'g',     'proteines'),
  ('Saucisse',              'manual', 'cat:saucisse',          'pièce', 'proteines'),
  ('Chipolata',             'manual', 'cat:chipolata',         'pièce', 'proteines'),
  ('Merguez',               'manual', 'cat:merguez',           'pièce', 'proteines'),
  ('Saucisson',             'manual', 'cat:saucisson',         'pièce', 'proteines'),
  ('Agneau',                'manual', 'cat:agneau',            'g',     'proteines'),
  ('Gigot d''agneau',       'manual', 'cat:gigot',             'g',     'proteines'),
  ('Côtelette d''agneau',   'manual', 'cat:cotelette-agneau',  'pièce', 'proteines'),
  ('Veau',                  'manual', 'cat:veau',              'g',     'proteines'),
  ('Escalope de veau',      'manual', 'cat:escalope-veau',     'pièce', 'proteines'),
  ('Canard',                'manual', 'cat:canard',            'g',     'proteines'),
  ('Magret de canard',      'manual', 'cat:magret-canard',     'pièce', 'proteines'),
  ('Lapin',                 'manual', 'cat:lapin',             'g',     'proteines'),
  -- Viandes & poissons — poissons & fruits de mer
  ('Cabillaud',             'manual', 'cat:cabillaud',         'g',     'proteines'),
  ('Colin',                 'manual', 'cat:colin',             'g',     'proteines'),
  ('Lieu',                  'manual', 'cat:lieu',              'g',     'proteines'),
  ('Truite',                'manual', 'cat:truite',            'pièce', 'proteines'),
  ('Dorade',                'manual', 'cat:dorade',            'pièce', 'proteines'),
  ('Bar',                   'manual', 'cat:bar',               'pièce', 'proteines'),
  ('Sole',                  'manual', 'cat:sole',              'pièce', 'proteines'),
  ('Sardine',               'manual', 'cat:sardine',           'g',     'proteines'),
  ('Maquereau',             'manual', 'cat:maquereau',         'pièce', 'proteines'),
  ('Anchois',               'manual', 'cat:anchois',           'g',     'proteines'),
  ('Crevette',              'manual', 'cat:crevette',          'g',     'proteines'),
  ('Gambas',                'manual', 'cat:gambas',            'g',     'proteines'),
  ('Moules',                'manual', 'cat:moules',            'g',     'proteines'),
  ('Calamar',               'manual', 'cat:calamar',           'g',     'proteines'),
  ('Saint-Jacques',         'manual', 'cat:saint-jacques',     'g',     'proteines'),
  ('Surimi',                'manual', 'cat:surimi',            'paquet','proteines'),
  ('Crabe',                 'manual', 'cat:crabe',             'boîte', 'proteines'),
  ('Sardines (boîte)',      'manual', 'cat:sardines-boite',    'boîte', 'proteines'),
  -- Crémerie & œufs
  ('Lait demi-écrémé',      'manual', 'cat:lait-demi-ecreme',  'L',     'cremerie'),
  ('Lait entier',           'manual', 'cat:lait-entier',       'L',     'cremerie'),
  ('Lait écrémé',           'manual', 'cat:lait-ecreme',       'L',     'cremerie'),
  ('Crème liquide',         'manual', 'cat:creme-liquide',     'cl',    'cremerie'),
  ('Margarine',             'manual', 'cat:margarine',         'g',     'cremerie'),
  ('Yaourt grec',           'manual', 'cat:yaourt-grec',       'pièce', 'cremerie'),
  ('Fromage blanc',         'manual', 'cat:fromage-blanc',     'g',     'cremerie'),
  ('Petit-suisse',          'manual', 'cat:petit-suisse',      'pièce', 'cremerie'),
  ('Skyr',                  'manual', 'cat:skyr',              'g',     'cremerie'),
  ('Comté',                 'manual', 'cat:comte',             'g',     'cremerie'),
  ('Gruyère',               'manual', 'cat:gruyere',           'g',     'cremerie'),
  ('Cheddar',               'manual', 'cat:cheddar',           'g',     'cremerie'),
  ('Feta',                  'manual', 'cat:feta',              'g',     'cremerie'),
  ('Chèvre',                'manual', 'cat:chevre',            'pièce', 'cremerie'),
  ('Brie',                  'manual', 'cat:brie',              'g',     'cremerie'),
  ('Roquefort',             'manual', 'cat:roquefort',         'g',     'cremerie'),
  ('Ricotta',               'manual', 'cat:ricotta',           'g',     'cremerie'),
  ('Mascarpone',            'manual', 'cat:mascarpone',        'g',     'cremerie'),
  ('Raclette',              'manual', 'cat:raclette',          'g',     'cremerie'),
  ('Crème dessert',         'manual', 'cat:creme-dessert',     'pièce', 'cremerie'),
  -- Pains & céréales
  ('Baguette',              'manual', 'cat:baguette',          'pièce', 'boulangerie'),
  ('Pain complet',          'manual', 'cat:pain-complet',      'pièce', 'boulangerie'),
  ('Pain aux céréales',     'manual', 'cat:pain-cereales',     'pièce', 'boulangerie'),
  ('Pain burger',           'manual', 'cat:pain-burger',       'paquet','boulangerie'),
  ('Biscotte',              'manual', 'cat:biscotte',          'paquet','boulangerie'),
  ('Wrap',                  'manual', 'cat:wrap',              'paquet','boulangerie'),
  ('Tortilla',              'manual', 'cat:tortilla',          'paquet','boulangerie'),
  ('Pâte feuilletée',       'manual', 'cat:pate-feuilletee',   'pièce', 'boulangerie'),
  ('Pâte brisée',           'manual', 'cat:pate-brisee',       'pièce', 'boulangerie'),
  ('Pâte sablée',           'manual', 'cat:pate-sablee',       'pièce', 'boulangerie'),
  ('Pâte à pizza',          'manual', 'cat:pate-pizza',        'pièce', 'boulangerie'),
  ('Chapelure',             'manual', 'cat:chapelure',         'g',     'boulangerie'),
  ('Farine complète',       'manual', 'cat:farine-complete',   'g',     'boulangerie'),
  ('Brioche',               'manual', 'cat:brioche',           'pièce', 'boulangerie'),
  ('Croissant',             'manual', 'cat:croissant',         'pièce', 'boulangerie'),
  ('Pita',                  'manual', 'cat:pita',              'paquet','boulangerie'),
  ('Naan',                  'manual', 'cat:naan',              'paquet','boulangerie'),
  -- Épicerie salée — féculents
  ('Spaghetti',             'manual', 'cat:spaghetti',         'g',     'epicerie'),
  ('Penne',                 'manual', 'cat:penne',             'g',     'epicerie'),
  ('Macaroni',              'manual', 'cat:macaroni',          'g',     'epicerie'),
  ('Tagliatelles',          'manual', 'cat:tagliatelles',      'g',     'epicerie'),
  ('Lasagnes',              'manual', 'cat:lasagnes',          'paquet','epicerie'),
  ('Coquillettes',          'manual', 'cat:coquillettes',      'g',     'epicerie'),
  ('Nouilles',              'manual', 'cat:nouilles',          'g',     'epicerie'),
  ('Gnocchi',               'manual', 'cat:gnocchi',           'g',     'epicerie'),
  ('Boulgour',              'manual', 'cat:boulgour',          'g',     'epicerie'),
  ('Polenta',               'manual', 'cat:polenta',           'g',     'epicerie'),
  ('Couscous',              'manual', 'cat:couscous',          'g',     'epicerie'),
  ('Riz basmati',           'manual', 'cat:riz-basmati',       'g',     'epicerie'),
  ('Riz complet',           'manual', 'cat:riz-complet',       'g',     'epicerie'),
  ('Flageolets',            'manual', 'cat:flageolets',        'boîte', 'epicerie'),
  ('Haricots blancs',       'manual', 'cat:haricots-blancs',   'boîte', 'epicerie'),
  -- Épicerie salée — sauces, conserves, huiles
  ('Maïs (boîte)',          'manual', 'cat:mais-boite',        'boîte', 'epicerie'),
  ('Sauce tomate',          'manual', 'cat:sauce-tomate',      'g',     'epicerie'),
  ('Coulis de tomate',      'manual', 'cat:coulis-tomate',     'g',     'epicerie'),
  ('Tomates concassées',    'manual', 'cat:tomates-concassees','boîte', 'epicerie'),
  ('Huile de colza',        'manual', 'cat:huile-colza',       'L',     'epicerie'),
  ('Huile de sésame',       'manual', 'cat:huile-sesame',      'ml',    'epicerie'),
  ('Vinaigre balsamique',   'manual', 'cat:vinaigre-balsamique','cl',   'epicerie'),
  ('Vinaigre de cidre',     'manual', 'cat:vinaigre-cidre',    'cl',    'epicerie'),
  ('Sauce soja',            'manual', 'cat:sauce-soja',        'ml',    'epicerie'),
  ('Nuoc-mâm',              'manual', 'cat:nuoc-mam',          'ml',    'epicerie'),
  ('Fond de veau',          'manual', 'cat:fond-veau',         'g',     'epicerie'),
  ('Bouillon de volaille',  'manual', 'cat:bouillon-volaille', 'pièce', 'epicerie'),
  ('Bouillon de légumes',   'manual', 'cat:bouillon-legumes',  'pièce', 'epicerie'),
  ('Bouillon de bœuf',      'manual', 'cat:bouillon-boeuf',    'pièce', 'epicerie'),
  ('Lait de coco',          'manual', 'cat:lait-coco',         'boîte', 'epicerie'),
  ('Crème de coco',         'manual', 'cat:creme-coco',        'boîte', 'epicerie'),
  ('Olives',                'manual', 'cat:olives',            'g',     'epicerie'),
  ('Cornichons',            'manual', 'cat:cornichons',        'g',     'epicerie'),
  ('Câpres',                'manual', 'cat:capres',            'g',     'epicerie'),
  -- Épicerie salée — épices & aides culinaires
  ('Curry',                 'manual', 'cat:curry',             'g',     'epicerie'),
  ('Paprika',               'manual', 'cat:paprika',           'g',     'epicerie'),
  ('Cumin',                 'manual', 'cat:cumin',             'g',     'epicerie'),
  ('Curcuma',               'manual', 'cat:curcuma',           'g',     'epicerie'),
  ('Cannelle',              'manual', 'cat:cannelle',          'g',     'epicerie'),
  ('Muscade',               'manual', 'cat:muscade',           'g',     'epicerie'),
  ('Gingembre moulu',       'manual', 'cat:gingembre-moulu',   'g',     'epicerie'),
  ('Piment en poudre',      'manual', 'cat:piment-poudre',     'g',     'epicerie'),
  ('Herbes de Provence',    'manual', 'cat:herbes-provence',   'g',     'epicerie'),
  ('Ras el hanout',         'manual', 'cat:ras-el-hanout',     'g',     'epicerie'),
  ('Quatre-épices',         'manual', 'cat:quatre-epices',     'g',     'epicerie'),
  ('Safran',                'manual', 'cat:safran',            'g',     'epicerie'),
  ('Vanille',               'manual', 'cat:vanille',           'pièce', 'epicerie'),
  ('Ail en poudre',         'manual', 'cat:ail-poudre',        'g',     'epicerie'),
  ('Maïzena',               'manual', 'cat:maizena',           'g',     'epicerie'),
  ('Gélatine',              'manual', 'cat:gelatine',          'sachet','epicerie'),
  ('Agar-agar',             'manual', 'cat:agar-agar',         'sachet','epicerie'),
  ('Bicarbonate',           'manual', 'cat:bicarbonate',       'g',     'epicerie'),
  ('Noix de coco râpée',    'manual', 'cat:coco-rapee',        'g',     'epicerie'),
  ('Chips',                 'manual', 'cat:chips',             'paquet','epicerie'),
  ('Cacahuètes',            'manual', 'cat:cacahuetes',        'g',     'epicerie'),
  ('Noix',                  'manual', 'cat:noix',              'g',     'epicerie'),
  ('Noisettes',             'manual', 'cat:noisettes',         'g',     'epicerie'),
  ('Amandes',               'manual', 'cat:amandes',           'g',     'epicerie'),
  ('Pignons',               'manual', 'cat:pignons',           'g',     'epicerie'),
  ('Raisins secs',          'manual', 'cat:raisins-secs',      'g',     'epicerie'),
  -- Épicerie sucrée & petit-déjeuner
  ('Sucre roux',            'manual', 'cat:sucre-roux',        'g',     'sucre'),
  ('Sucre vanillé',         'manual', 'cat:sucre-vanille',     'sachet','sucre'),
  ('Cassonade',             'manual', 'cat:cassonade',         'g',     'sucre'),
  ('Sucre glace',           'manual', 'cat:sucre-glace',       'g',     'sucre'),
  ('Chocolat noir',         'manual', 'cat:chocolat-noir',     'g',     'sucre'),
  ('Chocolat au lait',      'manual', 'cat:chocolat-lait',     'g',     'sucre'),
  ('Chocolat blanc',        'manual', 'cat:chocolat-blanc',    'g',     'sucre'),
  ('Pépites de chocolat',   'manual', 'cat:pepites-chocolat',  'g',     'sucre'),
  ('Cacao',                 'manual', 'cat:cacao',             'g',     'sucre'),
  ('Pâte à tartiner',       'manual', 'cat:pate-a-tartiner',   'g',     'sucre'),
  ('Sirop d''érable',       'manual', 'cat:sirop-erable',      'ml',    'sucre'),
  ('Compote',               'manual', 'cat:compote',           'pièce', 'sucre'),
  ('Thé vert',              'manual', 'cat:the-vert',          'sachet','sucre'),
  ('Infusion',              'manual', 'cat:infusion',          'sachet','sucre'),
  ('Flocons d''avoine',     'manual', 'cat:flocons-avoine',    'g',     'sucre'),
  ('Muesli',                'manual', 'cat:muesli',            'g',     'sucre'),
  ('Granola',               'manual', 'cat:granola',           'g',     'sucre'),
  ('Madeleines',            'manual', 'cat:madeleines',        'paquet','sucre'),
  ('Bonbons',               'manual', 'cat:bonbons',           'paquet','sucre'),
  -- Boissons
  ('Eau gazeuse',           'manual', 'cat:eau-gazeuse',       'L',     'boissons'),
  ('Jus de pomme',          'manual', 'cat:jus-pomme',         'L',     'boissons'),
  ('Jus multifruits',       'manual', 'cat:jus-multifruits',   'L',     'boissons'),
  ('Jus de raisin',         'manual', 'cat:jus-raisin',        'L',     'boissons'),
  ('Soda',                  'manual', 'cat:soda',              'L',     'boissons'),
  ('Cola',                  'manual', 'cat:cola',              'L',     'boissons'),
  ('Limonade',              'manual', 'cat:limonade',          'L',     'boissons'),
  ('Sirop de menthe',       'manual', 'cat:sirop-menthe',      'L',     'boissons'),
  ('Sirop de grenadine',    'manual', 'cat:sirop-grenadine',   'L',     'boissons'),
  ('Vin rouge',             'manual', 'cat:vin-rouge',         'pièce', 'boissons'),
  ('Vin blanc',             'manual', 'cat:vin-blanc',         'pièce', 'boissons'),
  ('Vin rosé',              'manual', 'cat:vin-rose',          'pièce', 'boissons'),
  ('Bière',                 'manual', 'cat:biere',             'pièce', 'boissons'),
  ('Champagne',             'manual', 'cat:champagne',         'pièce', 'boissons'),
  ('Cidre',                 'manual', 'cat:cidre',             'pièce', 'boissons'),
  ('Lait d''amande',        'manual', 'cat:lait-amande',       'L',     'boissons'),
  ('Lait de soja',          'manual', 'cat:lait-soja',         'L',     'boissons'),
  ('Lait d''avoine',        'manual', 'cat:lait-avoine',       'L',     'boissons'),
  -- Surgelés
  ('Épinards surgelés',     'manual', 'cat:epinards-surgeles', 'g',     'surgeles'),
  ('Poêlée de légumes',     'manual', 'cat:poelee-legumes',    'g',     'surgeles'),
  ('Petits pois surgelés',  'manual', 'cat:petits-pois-surgeles','g',   'surgeles'),
  ('Poisson pané',          'manual', 'cat:poisson-pane',      'paquet','surgeles'),
  ('Nuggets',               'manual', 'cat:nuggets',           'paquet','surgeles'),
  ('Cordon bleu',           'manual', 'cat:cordon-bleu',       'paquet','surgeles'),
  ('Pommes noisettes',      'manual', 'cat:pommes-noisettes',  'g',     'surgeles'),
  ('Sorbet',                'manual', 'cat:sorbet',            'L',     'surgeles'),
  ('Fruits surgelés',       'manual', 'cat:fruits-surgeles',   'g',     'surgeles'),
  -- Maison & entretien
  ('Liquide vaisselle',     'manual', 'cat:liquide-vaisselle', 'pièce', 'maison'),
  ('Lessive',               'manual', 'cat:lessive',           'pièce', 'maison'),
  ('Adoucissant',           'manual', 'cat:adoucissant',       'pièce', 'maison'),
  ('Éponge',                'manual', 'cat:eponge',            'paquet','maison'),
  ('Papier toilette',       'manual', 'cat:papier-toilette',   'paquet','maison'),
  ('Essuie-tout',           'manual', 'cat:essuie-tout',       'paquet','maison'),
  ('Sacs poubelle',         'manual', 'cat:sacs-poubelle',     'paquet','maison'),
  ('Film alimentaire',      'manual', 'cat:film-alimentaire',  'pièce', 'maison'),
  ('Papier aluminium',      'manual', 'cat:papier-alu',        'pièce', 'maison'),
  ('Papier cuisson',        'manual', 'cat:papier-cuisson',    'pièce', 'maison'),
  ('Nettoyant multi-usage', 'manual', 'cat:nettoyant-multi',   'pièce', 'maison'),
  ('Savon',                 'manual', 'cat:savon',             'pièce', 'maison'),
  ('Gel douche',            'manual', 'cat:gel-douche',        'pièce', 'maison'),
  ('Shampoing',             'manual', 'cat:shampoing',         'pièce', 'maison'),
  ('Dentifrice',            'manual', 'cat:dentifrice',        'pièce', 'maison'),
  ('Mouchoirs',             'manual', 'cat:mouchoirs',         'paquet','maison'),
  ('Tablettes lave-vaisselle','manual','cat:tablettes-lv',     'paquet','maison'),
  ('Eau de Javel',          'manual', 'cat:javel',             'pièce', 'maison')
on conflict (external_id) where source = 'manual' and external_id is not null
do update set
  name         = excluded.name,
  default_unit = excluded.default_unit,
  category     = excluded.category;

-- Conditionnements courants pour les nouveaux aliments les plus fréquents.
delete from public.food_package
where food_id in (
  select id from public.food where source = 'manual' and external_id = any (array[
    'cat:spaghetti','cat:penne','cat:riz-basmati','cat:blanc-poulet','cat:boeuf',
    'cat:saumon','cat:cabillaud','cat:lait-coco','cat:flocons-avoine','cat:lentilles',
    'cat:vin-rouge','cat:vin-blanc','cat:biere','cat:eau-gazeuse','cat:jus-pomme'
  ])
);

insert into public.food_package (food_id, label, quantity, unit, is_default, position)
select f.id, p.label, p.quantity, p.unit, p.is_default, p.position
from (values
  ('cat:spaghetti',    '500 g',      500, 'g',     true,  0),
  ('cat:spaghetti',    '1 kg',       1,   'kg',    false, 1),
  ('cat:penne',        '500 g',      500, 'g',     true,  0),
  ('cat:riz-basmati',  '1 kg',       1,   'kg',    true,  0),
  ('cat:riz-basmati',  '500 g',      500, 'g',     false, 1),
  ('cat:blanc-poulet', '500 g',      500, 'g',     true,  0),
  ('cat:blanc-poulet', '1 kg',       1,   'kg',    false, 1),
  ('cat:boeuf',        '500 g',      500, 'g',     true,  0),
  ('cat:boeuf',        '1 kg',       1,   'kg',    false, 1),
  ('cat:saumon',       '2 pavés',    2,   'pièce', true,  0),
  ('cat:cabillaud',    '500 g',      500, 'g',     true,  0),
  ('cat:lait-coco',    '40 cl',      40,  'cl',    true,  0),
  ('cat:flocons-avoine','500 g',     500, 'g',     true,  0),
  ('cat:vin-rouge',    'bouteille',  1,   'pièce', true,  0),
  ('cat:vin-blanc',    'bouteille',  1,   'pièce', true,  0),
  ('cat:biere',        'pack de 6',  6,   'pièce', true,  0),
  ('cat:eau-gazeuse',  'pack de 6',  6,   'pièce', true,  0),
  ('cat:jus-pomme',    '1 L',        1,   'L',     true,  0)
) as p(slug, label, quantity, unit, is_default, position)
join public.food f on f.external_id = p.slug and f.source = 'manual';
